In [1]:
import numpy as np

In [10]:
# Q.1 Convert a 1D array to a 2D array with 2 rows 

arr1 = np.array([11,22,33,44,55,66,77,88,99,100])

arr2 = arr1.reshape(2,-1)

print("arr1 :",arr1)
print("arr2 :",arr2)


arr1 : [ 11  22  33  44  55  66  77  88  99 100]
arr2 : [[ 11  22  33  44  55]
 [ 66  77  88  99 100]]


In [12]:
# Q.2 Get the common items between a and b 

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

common_items = np.intersect1d(a, b)

common_items

array([2, 4])

In [22]:
# Q.3 Get all items between 5 and 10 from a.

a = np.array([2,6,1,9,10,3,27])
b = a[(a >= 5) & (a <= 10)]

b

array([ 6,  9, 10])

In [25]:
# Q.4 Limit the number of items printed in python NumPy array a to a maximum of 6 elements.

a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])

if len(a) > 6:
    print(np.concatenate([a[:3], ['...'], a[-3:]]))
else:
    print(a)

['0' '1' '2' '...' '12' '13' '14']
